### PR TITLE
[WIP] Added Formulas to Calculate Liquidation Price of Exchanges

### PR DESCRIPTION
**Pull request by arunavo4**
https://www.binance.com/en/support/faq/b3c689c1f50a44cabb3a84e663b81d93
Liquidation Price of USDⓈ-M Futures Contracts

## Summary
Calculate Liquidation Price of Exchanges

### CODE REVIEW

**Comment by arunavo4** [comment]
The Calculation for Liquidation Price of USDⓈ-M Futures Contracts is there.
Unable to understand the formula for Margin Trading.

**Comment by arunavo4** [comment]
I will be adding the test for Liquidation Price of USDⓈ-M Futures Contracts

**Comment by samgermain** [comment]
I'm going to just merge this in, and then your changes will be present on the freqtrade PR

**Comment by samgermain** [comment]
Also are you using 2 github accounts? I would recommend using just one, so that all your accomplishments are visible from your one account

**Comment by arunavo4** [comment]
> Also are you using 2 github accounts? I would recommend using just one, so that all your accomplishments are visible from your one account

actually, I forgot to change my git user.email

**Pull request merged**
